"""Convert a standard or extended message to a topic."""
from ...constants import MessageFlagType, DeviceCategory
from ..messages.user_data import UserData
from ...address import Address

from ...topics import (
    IO_OUTPUT_ON,
    IO_OUTPUT_OFF,
    IO_ALARM_DATA_REQUEST,
    IO_WRITE_OUTPUT_PORT,
    IO_READ_INPUT_PORT,
    IO_GET_SENSOR_VALUE,
    IO_SET_SENSOR_1_NOMINAL_VALUE,
    IO_GET_SENSOR_ALARM_DELTA,
    IO_WRITE_CONFIGURATION_PORT,
    IO_READ_CONFIGURATION_PORT,
    IO_SET_SENSOR_NOMINAL_VALUE,
    IO_ALARM_DATA_RESPONSE,

    IO_MODULE_LOAD_INITIALIZATION_VALUES,
    IO_MODULE_LOAD_EEPROM_FROM_RAM,
    IO_MODULE_STATUS_REQUEST,
    IO_MODULE_READ_ANALOG_ONCE,
    IO_MODULE_READ_ANALOG_ALWAYS,
    IO_MODULE_ENABLE_STATUS_CHANGE_MESSAGE,
    IO_MODULE_DISABLE_STATUS_CHANGE_MESSAGE,
    IO_MODULE_LOAD_RAM_FROM_EEPROM,
    IO_MODULE_SENSOR_ON,
    IO_MODULE_SENSOR_OFF,
    IO_MODULE_DIAGNOSTICS_ON,
    IO_MODULE_DIAGNOSTICS_OFF,)