"""Convert a standard or extended message to a topic."""
from ...constants import MessageFlagType, DeviceCategory
from ..messages.user_data import UserData
from ...address import Address

from ...topics import (
    SPRINKLER_VALVE_ON,
    SPRINKLER_VALVE_OFF,
    SPRINKLER_PROGRAM_ON,
    SPRINKLER_PROGRAM_OFF,
    SPRINKLER_LOAD_INITIALIZATION_VALUES,
    SPRINKLER_LOAD_EEPROM_FROM_RAM,
    SPRINKLER_GET_VALVE_STATUS,
    SPRINKLER_INHIBIT_COMMAND_ACCEPTANCE,
    SPRINKLER_RESUME_COMMAND_ACCEPTANCE,
    SPRINKLER_SKIP_FORWARD,
    SPRINKLER_SKIP_BACK,
    SPRINKLER_ENABLE_PUMP_ON_V8,
    SPRINKLER_DISABLE_PUMP_ON_V8,
    SPRINKLER_BROADCAST_ON,
    SPRINKLER_BROADCAST_OFF,
    SPRINKLER_LOAD_RAM_FROM_EEPROM,
    SPRINKLER_SENSOR_ON,
    SPRINKLER_SENSOR_OFF,
    SPRINKLER_DIAGNOSTICS_ON,
    SPRINKLER_DIAGNOSTICS_OFF,
    SPRINKLER_GET_PROGRAM_REQUEST,)

