version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    dev-dependencies:
      patterns:
        - "flake8-docstrings"
        - "flake8"
        - "flake8-noqa"
        - "flake8-comprehensions"
        - "pyflakes"
        - "pycodestyle"
        - "pydocstyle"
        - "pylint"
        - "isort"
        - "async_generator"
        - "black"
        - "pytest-cov"
        - "pytest"
        - "pre-commit"

