# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  - name: PythonMain
    value: '3.7'
  - name: BlackVersion
    value: '19.10b0'

stages:
- stage: 'Code_check'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'pylint'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PythonMain)'
      displayName: 'Use Python main version.'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
        pip install black=='$(BlackVersion)'
      displayName: 'Install dependencies'
    - script: |
        pylint pyinsteon
      displayName: 'pylint'
    - script: |
        flake8 pyinsteon
      displayName: 'flake8'
    - script: |
        black pyinsteon
      displayName: 'black'

- stage: 'Tests'
  jobs:
  - job: 'PyTest'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
      displayName: 'Install dependencies'

    - script: |
        python -m unittest -b -v
      displayName: 'Unit test'