"""Device state definitions."""
DIMMABLE_LIGHT = "dimmable_light"
DIMMABLE_FAN = "dimmable_fan"
DIMMABLE_OUTLET = "dimmable_outlet"
ON_OFF_SWITCH = "on_off_switch"
RELAY = "RELAY"
ON_OFF_OUTLET_TOP = "on_off_outlet_top"
ON_OFF_OUTLET_BOTTOM = "on_off_outlet_bottom"
LOW_BATTERY = "low_battery"
OPEN_CLOSE_SENSOR = "open_close_sensor"
LIGHT_SENSOR = "light_sensor"
LEAK_SENSOR_DRY = "leak_sensor_dry"
LEAK_SENSOR_WET = "leak_sensor_wet"
DOOR_SENSOR = "door_sensor"
MOTION_SENSOR = "motion_sensor"
SMOKE_SENSOR = "smoke_sensor"
CO_SENSOR = "co_sensor"
TEST_SENSOR = "test_sensor"
NEW_SENSOR = "new_sensor"
HEARTBEAT = "heartbeat"
SENSOR_MALFUNCTION = "sensor_malfunction"
COVER = "cover"
COOL_SET_POINT = "cool_set_point"
HEAT_SET_POINT = "heat_set_point"
HUMIDITY_HIGH = "humidity_high"
HUMIDITY_LOW = "humidity_low"
SYSTEM_MODE = "system_mode"
FAN_MODE = "fan_mode"
TEMPERATURE = "temperature"
HUMIDITY = "humidity"
COOLING = "cooling"
HEATING = "heating"
HUMIDIFYING = "humidifying"
DEHUMIDIFYING = "dehumidifying"

ON_OFF_SWITCH_MAIN = "{}_{}".format(ON_OFF_SWITCH, "main")
ON_OFF_SWITCH_A = "{}_{}".format(ON_OFF_SWITCH, "a")
ON_OFF_SWITCH_B = "{}_{}".format(ON_OFF_SWITCH, "b")
ON_OFF_SWITCH_C = "{}_{}".format(ON_OFF_SWITCH, "c")
ON_OFF_SWITCH_D = "{}_{}".format(ON_OFF_SWITCH, "d")
ON_OFF_SWITCH_E = "{}_{}".format(ON_OFF_SWITCH, "e")
ON_OFF_SWITCH_F = "{}_{}".format(ON_OFF_SWITCH, "f")
ON_OFF_SWITCH_G = "{}_{}".format(ON_OFF_SWITCH, "g")
ON_OFF_SWITCH_H = "{}_{}".format(ON_OFF_SWITCH, "h")

DIMMABLE_LIGHT_MAIN = "{}_{}".format(DIMMABLE_LIGHT, "main")
# DIMMABLE_LIGHT_A = '{}_{}'.format(DIMMABLE_LIGHT, 'a')
# DIMMABLE_LIGHT_B = '{}_{}'.format(DIMMABLE_LIGHT, 'b')
# DIMMABLE_LIGHT_C = '{}_{}'.format(DIMMABLE_LIGHT, 'c')
# DIMMABLE_LIGHT_D = '{}_{}'.format(DIMMABLE_LIGHT, 'd')
# DIMMABLE_LIGHT_E = '{}_{}'.format(DIMMABLE_LIGHT, 'e')
# DIMMABLE_LIGHT_F = '{}_{}'.format(DIMMABLE_LIGHT, 'f')
# DIMMABLE_LIGHT_G = '{}_{}'.format(DIMMABLE_LIGHT, 'g')
# DIMMABLE_LIGHT_H = '{}_{}'.format(DIMMABLE_LIGHT, 'h')
