# Automatically generated by TopicTreeSpecPrinter(**kwargs).
# The kwargs were:
# - fileObj: TextIOWrapper
# - footer: '# End of topic tree definition. Note that application may l...'
# - indentStep: 4
# - treeDoc: None
# - width: 70


class command:
    """
    Device command.
    """

    class off:
        """
        Device Off command.
        """

        class all_link_broadcast:
            """
            Device Off all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Off all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Off all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Off all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Off broadcast command.
            """

        class direct:
            """
            Device Off direct command.
            """

        class direct_ack:
            """
            Device Off direct_ack command.
            """

        class direct_nak:
            """
            Device Off direct_nak command.
            """

    class on:
        """
        Device ON command.
        """

        class all_link_broadcast:
            """
            Device ON all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device ON all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device ON all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device ON all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device ON broadcast command.
            """

        class direct:
            """
            Device ON direct command.
            """

        class direct_ack:
            """
            Device ON direct_ack command.
            """

        class direct_nak:
            """
            Device ON direct_nak command.
            """

    class assign_to_all_link_group:
        """
        Device Assign to ALL-Link Group command.
        """

        class all_link_broadcast:
            """
            Device Assign to ALL-Link Group all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Assign to ALL-Link Group all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Assign to ALL-Link Group all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Assign to ALL-Link Group all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Assign to ALL-Link Group broadcast command.
            """

        class direct:
            """
            Device Assign to ALL-Link Group direct command.
            """

        class direct_ack:
            """
            Device Assign to ALL-Link Group direct_ack command.
            """

        class direct_nak:
            """
            Device Assign to ALL-Link Group direct_nak command.
            """

    class assign_to_companion_group:
        """
        Device Assign to Companion Group command.
        """

        class all_link_broadcast:
            """
            Device Assign to Companion Group all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Assign to Companion Group all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Assign to Companion Group all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Assign to Companion Group all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Assign to Companion Group broadcast command.
            """

        class direct:
            """
            Device Assign to Companion Group direct command.
            """

        class direct_ack:
            """
            Device Assign to Companion Group direct_ack command.
            """

        class direct_nak:
            """
            Device Assign to Companion Group direct_nak command.
            """

    class block_data_transfer:
        """
        Device Block Data Transfer command.
        """

        class all_link_broadcast:
            """
            Device Block Data Transfer all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Block Data Transfer all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Block Data Transfer all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Block Data Transfer all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Block Data Transfer broadcast command.
            """

        class direct:
            """
            Device Block Data Transfer direct command.
            """

        class direct_ack:
            """
            Device Block Data Transfer direct_ack command.
            """

        class direct_nak:
            """
            Device Block Data Transfer direct_nak command.
            """

    class brighten_one_step:
        """
        Device Brighten One Step  command.
        """

        class all_link_broadcast:
            """
            Device Brighten One Step  all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Brighten One Step  all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Brighten One Step  all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Brighten One Step  all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Brighten One Step  broadcast command.
            """

        class direct:
            """
            Device Brighten One Step  direct command.
            """

        class direct_ack:
            """
            Device Brighten One Step  direct_ack command.
            """

        class direct_nak:
            """
            Device Brighten One Step  direct_nak command.
            """

    class delete_from_all_link_group:
        """
        Device Delete from ALL-Link Group command.
        """

        class all_link_broadcast:
            """
            Device Delete from ALL-Link Group all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Delete from ALL-Link Group all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Delete from ALL-Link Group all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Delete from ALL-Link Group all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Delete from ALL-Link Group broadcast command.
            """

        class direct:
            """
            Device Delete from ALL-Link Group direct command.
            """

        class direct_ack:
            """
            Device Delete from ALL-Link Group direct_ack command.
            """

        class direct_nak:
            """
            Device Delete from ALL-Link Group direct_nak command.
            """

    class device_text_string_request:
        """
        Device Device Text String Request command.
        """

        class all_link_broadcast:
            """
            Device Device Text String Request all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Device Text String Request all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Device Text String Request all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Device Text String Request all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Device Text String Request broadcast command.
            """

        class direct:
            """
            Device Device Text String Request direct command.
            """

        class direct_ack:
            """
            Device Device Text String Request direct_ack command.
            """

        class direct_nak:
            """
            Device Device Text String Request direct_nak command.
            """

    class dim_one_step:
        """
        Device Dim One Step command.
        """

        class all_link_broadcast:
            """
            Device Dim One Step all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Dim One Step all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Dim One Step all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Dim One Step all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Dim One Step broadcast command.
            """

        class direct:
            """
            Device Dim One Step direct command.
            """

        class direct_ack:
            """
            Device Dim One Step direct_ack command.
            """

        class direct_nak:
            """
            Device Dim One Step direct_nak command.
            """

    class door_move:
        """
        Device Door Move command.
        """

        class all_link_broadcast:
            """
            Device Door Move all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Door Move all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Door Move all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Door Move all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Door Move broadcast command.
            """

        class direct:
            """
            Device Door Move direct command.
            """

        class direct_ack:
            """
            Device Door Move direct_ack command.
            """

        class direct_nak:
            """
            Device Door Move direct_nak command.
            """

    class door_status_report:
        """
        Device Door Status Report command.
        """

        class all_link_broadcast:
            """
            Device Door Status Report all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Door Status Report all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Door Status Report all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Door Status Report all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Door Status Report broadcast command.
            """

        class direct:
            """
            Device Door Status Report direct command.
            """

        class direct_ack:
            """
            Device Door Status Report direct_ack command.
            """

        class direct_nak:
            """
            Device Door Status Report direct_nak command.
            """

    class enter_linking_mode:
        """
        Device Enter Linking Mode command.
        """

        class all_link_broadcast:
            """
            Device Enter Linking Mode all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Enter Linking Mode all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Enter Linking Mode all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Enter Linking Mode all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Enter Linking Mode broadcast command.
            """

        class direct:
            """
            Device Enter Linking Mode direct command.
            """

        class direct_ack:
            """
            Device Enter Linking Mode direct_ack command.
            """

        class direct_nak:
            """
            Device Enter Linking Mode direct_nak command.
            """

    class enter_unlinking_mode:
        """
        Device Enter Unlinking Mode command.
        """

        class all_link_broadcast:
            """
            Device Enter Unlinking Mode all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Enter Unlinking Mode all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Enter Unlinking Mode all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Enter Unlinking Mode all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Enter Unlinking Mode broadcast command.
            """

        class direct:
            """
            Device Enter Unlinking Mode direct command.
            """

        class direct_ack:
            """
            Device Enter Unlinking Mode direct_ack command.
            """

        class direct_nak:
            """
            Device Enter Unlinking Mode direct_nak command.
            """

    class extended_set_get:
        """
        Device Extended Set/Get command.
        """

        class all_link_broadcast:
            """
            Device Extended Set/Get all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Extended Set/Get all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Extended Set/Get all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Extended Set/Get all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Extended Set/Get broadcast command.
            """

        class direct:
            """
            Device Extended Set/Get direct command.
            """

        class direct_ack:
            """
            Device Extended Set/Get direct_ack command.
            """

        class direct_nak:
            """
            Device Extended Set/Get direct_nak command.
            """

    class fan_status_report:
        """
        Device Fan Status Report command.
        """

        class all_link_broadcast:
            """
            Device Fan Status Report all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Fan Status Report all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Fan Status Report all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Fan Status Report all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Fan Status Report broadcast command.
            """

        class direct:
            """
            Device Fan Status Report direct command.
            """

        class direct_ack:
            """
            Device Fan Status Report direct_ack command.
            """

        class direct_nak:
            """
            Device Fan Status Report direct_nak command.
            """

    class flash_led:
        """
        Device Flash LED command.
        """

        class all_link_broadcast:
            """
            Device Flash LED all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Flash LED all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Flash LED all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Flash LED all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Flash LED broadcast command.
            """

        class direct:
            """
            Device Flash LED direct command.
            """

        class direct_ack:
            """
            Device Flash LED direct_ack command.
            """

        class direct_nak:
            """
            Device Flash LED direct_nak command.
            """

    class fx_username:
        """
        Device FX Username command.
        """

        class all_link_broadcast:
            """
            Device FX Username all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device FX Username all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device FX Username all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device FX Username all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device FX Username broadcast command.
            """

        class direct:
            """
            Device FX Username direct command.
            """

        class direct_ack:
            """
            Device FX Username direct_ack command.
            """

        class direct_nak:
            """
            Device FX Username direct_nak command.
            """

    class get_insteon_engine_version:
        """
        Device Get INSTEON Engine Version command.
        """

        class all_link_broadcast:
            """
            Device Get INSTEON Engine Version all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Get INSTEON Engine Version all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Get INSTEON Engine Version all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Get INSTEON Engine Version all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Get INSTEON Engine Version broadcast command.
            """

        class direct:
            """
            Device Get INSTEON Engine Version direct command.
            """

        class direct_ack:
            """
            Device Get INSTEON Engine Version direct_ack command.
            """

        class direct_nak:
            """
            Device Get INSTEON Engine Version direct_nak command.
            """

    class get_operating_flags:
        """
        Device Get Operating Flags command.
        """

        class all_link_broadcast:
            """
            Device Get Operating Flags all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Get Operating Flags all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Get Operating Flags all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Get Operating Flags all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Get Operating Flags broadcast command.
            """

        class direct:
            """
            Device Get Operating Flags direct command.
            """

        class direct_ack:
            """
            Device Get Operating Flags direct_ack command.
            """

        class direct_nak:
            """
            Device Get Operating Flags direct_nak command.
            """

    class io_alarm_data_request:
        """
        Device I/O Alarm Data Request command.
        """

        class all_link_broadcast:
            """
            Device I/O Alarm Data Request all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Alarm Data Request all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Alarm Data Request all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Alarm Data Request all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Alarm Data Request broadcast command.
            """

        class direct:
            """
            Device I/O Alarm Data Request direct command.
            """

        class direct_ack:
            """
            Device I/O Alarm Data Request direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Alarm Data Request direct_nak command.
            """

    class io_alarm_data_response:
        """
        Device I/O Alarm Data Response command.
        """

        class all_link_broadcast:
            """
            Device I/O Alarm Data Response all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Alarm Data Response all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Alarm Data Response all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Alarm Data Response all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Alarm Data Response broadcast command.
            """

        class direct:
            """
            Device I/O Alarm Data Response direct command.
            """

        class direct_ack:
            """
            Device I/O Alarm Data Response direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Alarm Data Response direct_nak command.
            """

    class io_get_sensor_alarm_delta:
        """
        Device I/O Get Sensor Alarm Delta command.
        """

        class all_link_broadcast:
            """
            Device I/O Get Sensor Alarm Delta all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Get Sensor Alarm Delta all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Get Sensor Alarm Delta all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Get Sensor Alarm Delta all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Get Sensor Alarm Delta broadcast command.
            """

        class direct:
            """
            Device I/O Get Sensor Alarm Delta direct command.
            """

        class direct_ack:
            """
            Device I/O Get Sensor Alarm Delta direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Get Sensor Alarm Delta direct_nak command.
            """

    class io_get_sensor_value:
        """
        Device I/O Get Sensor Value command.
        """

        class all_link_broadcast:
            """
            Device I/O Get Sensor Value all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Get Sensor Value all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Get Sensor Value all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Get Sensor Value all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Get Sensor Value broadcast command.
            """

        class direct:
            """
            Device I/O Get Sensor Value direct command.
            """

        class direct_ack:
            """
            Device I/O Get Sensor Value direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Get Sensor Value direct_nak command.
            """

    class io_module_control:
        """
        Device I/O Module Control command.
        """

        class all_link_broadcast:
            """
            Device I/O Module Control all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Module Control all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Module Control all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Module Control all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Module Control broadcast command.
            """

        class direct:
            """
            Device I/O Module Control direct command.
            """

        class direct_ack:
            """
            Device I/O Module Control direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Module Control direct_nak command.
            """

    class io_output_off:
        """
        Device I/O Output Off command.
        """

        class all_link_broadcast:
            """
            Device I/O Output Off all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Output Off all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Output Off all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Output Off all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Output Off broadcast command.
            """

        class direct:
            """
            Device I/O Output Off direct command.
            """

        class direct_ack:
            """
            Device I/O Output Off direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Output Off direct_nak command.
            """

    class io_output_on:
        """
        Device I/O Output On command.
        """

        class all_link_broadcast:
            """
            Device I/O Output On all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Output On all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Output On all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Output On all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Output On broadcast command.
            """

        class direct:
            """
            Device I/O Output On direct command.
            """

        class direct_ack:
            """
            Device I/O Output On direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Output On direct_nak command.
            """

    class io_read_configuration_port:
        """
        Device I/O Read Configuration Port command.
        """

        class all_link_broadcast:
            """
            Device I/O Read Configuration Port all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Read Configuration Port all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Read Configuration Port all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Read Configuration Port all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Read Configuration Port broadcast command.
            """

        class direct:
            """
            Device I/O Read Configuration Port direct command.
            """

        class direct_ack:
            """
            Device I/O Read Configuration Port direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Read Configuration Port direct_nak command.
            """

    class io_read_input_port:
        """
        Device I/O Read Input Port command.
        """

        class all_link_broadcast:
            """
            Device I/O Read Input Port all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Read Input Port all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Read Input Port all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Read Input Port all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Read Input Port broadcast command.
            """

        class direct:
            """
            Device I/O Read Input Port direct command.
            """

        class direct_ack:
            """
            Device I/O Read Input Port direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Read Input Port direct_nak command.
            """

    class io_set_sensor_1_nominal_value:
        """
        Device I/O Set Sensor 1 Nominal Value command.
        """

        class all_link_broadcast:
            """
            Device I/O Set Sensor 1 Nominal Value all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Set Sensor 1 Nominal Value all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Set Sensor 1 Nominal Value all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Set Sensor 1 Nominal Value all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Set Sensor 1 Nominal Value broadcast command.
            """

        class direct:
            """
            Device I/O Set Sensor 1 Nominal Value direct command.
            """

        class direct_ack:
            """
            Device I/O Set Sensor 1 Nominal Value direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Set Sensor 1 Nominal Value direct_nak command.
            """

    class io_set_sensor_nominal:
        """
        Device I/O Set Sensor Nominal command.
        """

        class all_link_broadcast:
            """
            Device I/O Set Sensor Nominal all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Set Sensor Nominal all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Set Sensor Nominal all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Set Sensor Nominal all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Set Sensor Nominal broadcast command.
            """

        class direct:
            """
            Device I/O Set Sensor Nominal direct command.
            """

        class direct_ack:
            """
            Device I/O Set Sensor Nominal direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Set Sensor Nominal direct_nak command.
            """

    class io_write_configuration_port:
        """
        Device I/O Write Configuration Port command.
        """

        class all_link_broadcast:
            """
            Device I/O Write Configuration Port all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Write Configuration Port all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Write Configuration Port all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Write Configuration Port all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Write Configuration Port broadcast command.
            """

        class direct:
            """
            Device I/O Write Configuration Port direct command.
            """

        class direct_ack:
            """
            Device I/O Write Configuration Port direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Write Configuration Port direct_nak command.
            """

    class io_write_output_port:
        """
        Device I/O Write Output Port command.
        """

        class all_link_broadcast:
            """
            Device I/O Write Output Port all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device I/O Write Output Port all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device I/O Write Output Port all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device I/O Write Output Port all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device I/O Write Output Port broadcast command.
            """

        class direct:
            """
            Device I/O Write Output Port direct command.
            """

        class direct_ack:
            """
            Device I/O Write Output Port direct_ack command.
            """

        class direct_nak:
            """
            Device I/O Write Output Port direct_nak command.
            """

    class id_request:
        """
        Device ID Request command.
        """

        class all_link_broadcast:
            """
            Device ID Request all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device ID Request all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device ID Request all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device ID Request all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device ID Request broadcast command.
            """

        class direct:
            """
            Device ID Request direct command.
            """

        class direct_ack:
            """
            Device ID Request direct_ack command.
            """

        class direct_nak:
            """
            Device ID Request direct_nak command.
            """

    class leak_detector_announce:
        """
        Device Leak Detector Announce command.
        """

        class all_link_broadcast:
            """
            Device Leak Detector Announce all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Leak Detector Announce all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Leak Detector Announce all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Leak Detector Announce all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Leak Detector Announce broadcast command.
            """

        class direct:
            """
            Device Leak Detector Announce direct command.
            """

        class direct_ack:
            """
            Device Leak Detector Announce direct_ack command.
            """

        class direct_nak:
            """
            Device Leak Detector Announce direct_nak command.
            """

    class light_instant_change:
        """
        Device Light Instant Change command.
        """

        class all_link_broadcast:
            """
            Device Light Instant Change all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Light Instant Change all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Light Instant Change all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Light Instant Change all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Light Instant Change broadcast command.
            """

        class direct:
            """
            Device Light Instant Change direct command.
            """

        class direct_ack:
            """
            Device Light Instant Change direct_ack command.
            """

        class direct_nak:
            """
            Device Light Instant Change direct_nak command.
            """

    class light_manually_turned_off:
        """
        Device Light Manually Turned Off command.
        """

        class all_link_broadcast:
            """
            Device Light Manually Turned Off all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Light Manually Turned Off all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Light Manually Turned Off all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Light Manually Turned Off all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Light Manually Turned Off broadcast command.
            """

        class direct:
            """
            Device Light Manually Turned Off direct command.
            """

        class direct_ack:
            """
            Device Light Manually Turned Off direct_ack command.
            """

        class direct_nak:
            """
            Device Light Manually Turned Off direct_nak command.
            """

    class light_off_at_ramp_rate:
        """
        Device Light OFF at Ramp Rate command.
        """

        class all_link_broadcast:
            """
            Device Light OFF at Ramp Rate all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Light OFF at Ramp Rate all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Light OFF at Ramp Rate all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Light OFF at Ramp Rate all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Light OFF at Ramp Rate broadcast command.
            """

        class direct:
            """
            Device Light OFF at Ramp Rate direct command.
            """

        class direct_ack:
            """
            Device Light OFF at Ramp Rate direct_ack command.
            """

        class direct_nak:
            """
            Device Light OFF at Ramp Rate direct_nak command.
            """

    class light_on_at_ramp_rate:
        """
        Device Light ON at Ramp Rate command.
        """

        class all_link_broadcast:
            """
            Device Light ON at Ramp Rate all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Light ON at Ramp Rate all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Light ON at Ramp Rate all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Light ON at Ramp Rate all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Light ON at Ramp Rate broadcast command.
            """

        class direct:
            """
            Device Light ON at Ramp Rate direct command.
            """

        class direct_ack:
            """
            Device Light ON at Ramp Rate direct_ack command.
            """

        class direct_nak:
            """
            Device Light ON at Ramp Rate direct_nak command.
            """

    class light_set_status:
        """
        Device Light Set Status command.
        """

        class all_link_broadcast:
            """
            Device Light Set Status all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Light Set Status all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Light Set Status all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Light Set Status all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Light Set Status broadcast command.
            """

        class direct:
            """
            Device Light Set Status direct command.
            """

        class direct_ack:
            """
            Device Light Set Status direct_ack command.
            """

        class direct_nak:
            """
            Device Light Set Status direct_nak command.
            """

    class off_fast:
        """
        Device Off Fast command.
        """

        class all_link_broadcast:
            """
            Device Off Fast all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Off Fast all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Off Fast all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Off Fast all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Off Fast broadcast command.
            """

        class direct:
            """
            Device Off Fast direct command.
            """

        class direct_ack:
            """
            Device Off Fast direct_ack command.
            """

        class direct_nak:
            """
            Device Off Fast direct_nak command.
            """

    class on_fast:
        """
        Device On Fast command.
        """

        class all_link_broadcast:
            """
            Device On Fast all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device On Fast all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device On Fast all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device On Fast all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device On Fast broadcast command.
            """

        class direct:
            """
            Device On Fast direct command.
            """

        class direct_ack:
            """
            Device On Fast direct_ack command.
            """

        class direct_nak:
            """
            Device On Fast direct_nak command.
            """

    class peek_one_byte:
        """
        Device Peek One Byte command.
        """

        class all_link_broadcast:
            """
            Device Peek One Byte all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Peek One Byte all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Peek One Byte all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Peek One Byte all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Peek One Byte broadcast command.
            """

        class direct:
            """
            Device Peek One Byte direct command.
            """

        class direct_ack:
            """
            Device Peek One Byte direct_ack command.
            """

        class direct_nak:
            """
            Device Peek One Byte direct_nak command.
            """

    class peek_one_byte_internal:
        """
        Device Peek One Byte Internal command.
        """

        class all_link_broadcast:
            """
            Device Peek One Byte Internal all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Peek One Byte Internal all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Peek One Byte Internal all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Peek One Byte Internal all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Peek One Byte Internal broadcast command.
            """

        class direct:
            """
            Device Peek One Byte Internal direct command.
            """

        class direct_ack:
            """
            Device Peek One Byte Internal direct_ack command.
            """

        class direct_nak:
            """
            Device Peek One Byte Internal direct_nak command.
            """

    class ping:
        """
        Device Ping command.
        """

        class all_link_broadcast:
            """
            Device Ping all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Ping all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Ping all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Ping all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Ping broadcast command.
            """

        class direct:
            """
            Device Ping direct command.
            """

        class direct_ack:
            """
            Device Ping direct_ack command.
            """

        class direct_nak:
            """
            Device Ping direct_nak command.
            """

    class poke_one_byte:
        """
        Device Poke One Byte command.
        """

        class all_link_broadcast:
            """
            Device Poke One Byte all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Poke One Byte all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Poke One Byte all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Poke One Byte all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Poke One Byte broadcast command.
            """

        class direct:
            """
            Device Poke One Byte direct command.
            """

        class direct_ack:
            """
            Device Poke One Byte direct_ack command.
            """

        class direct_nak:
            """
            Device Poke One Byte direct_nak command.
            """

    class poke_one_byte_internal:
        """
        Device Poke One Byte Internal command.
        """

        class all_link_broadcast:
            """
            Device Poke One Byte Internal all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Poke One Byte Internal all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Poke One Byte Internal all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Poke One Byte Internal all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Poke One Byte Internal broadcast command.
            """

        class direct:
            """
            Device Poke One Byte Internal direct command.
            """

        class direct_ack:
            """
            Device Poke One Byte Internal direct_ack command.
            """

        class direct_nak:
            """
            Device Poke One Byte Internal direct_nak command.
            """

    class pool_control:
        """
        Device Pool Control command.
        """

        class all_link_broadcast:
            """
            Device Pool Control all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Pool Control all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Pool Control all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Pool Control all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Pool Control broadcast command.
            """

        class direct:
            """
            Device Pool Control direct command.
            """

        class direct_ack:
            """
            Device Pool Control direct_ack command.
            """

        class direct_nak:
            """
            Device Pool Control direct_nak command.
            """

    class pool_device_off:
        """
        Device Pool Device OFF command.
        """

        class all_link_broadcast:
            """
            Device Pool Device OFF all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Pool Device OFF all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Pool Device OFF all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Pool Device OFF all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Pool Device OFF broadcast command.
            """

        class direct:
            """
            Device Pool Device OFF direct command.
            """

        class direct_ack:
            """
            Device Pool Device OFF direct_ack command.
            """

        class direct_nak:
            """
            Device Pool Device OFF direct_nak command.
            """

    class pool_device_on:
        """
        Device Pool Device ON command.
        """

        class all_link_broadcast:
            """
            Device Pool Device ON all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Pool Device ON all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Pool Device ON all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Pool Device ON all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Pool Device ON broadcast command.
            """

        class direct:
            """
            Device Pool Device ON direct command.
            """

        class direct_ack:
            """
            Device Pool Device ON direct_ack command.
            """

        class direct_nak:
            """
            Device Pool Device ON direct_nak command.
            """

    class pool_set_device_hysteresis:
        """
        Device Pool Set Device Hysteresis command.
        """

        class all_link_broadcast:
            """
            Device Pool Set Device Hysteresis all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Pool Set Device Hysteresis all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Pool Set Device Hysteresis all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Pool Set Device Hysteresis all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Pool Set Device Hysteresis broadcast command.
            """

        class direct:
            """
            Device Pool Set Device Hysteresis direct command.
            """

        class direct_ack:
            """
            Device Pool Set Device Hysteresis direct_ack command.
            """

        class direct_nak:
            """
            Device Pool Set Device Hysteresis direct_nak command.
            """

    class pool_set_device_temperature:
        """
        Device Pool Set Device Temperature command.
        """

        class all_link_broadcast:
            """
            Device Pool Set Device Temperature all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Pool Set Device Temperature all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Pool Set Device Temperature all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Pool Set Device Temperature all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Pool Set Device Temperature broadcast command.
            """

        class direct:
            """
            Device Pool Set Device Temperature direct command.
            """

        class direct_ack:
            """
            Device Pool Set Device Temperature direct_ack command.
            """

        class direct_nak:
            """
            Device Pool Set Device Temperature direct_nak command.
            """

    class pool_temperature_down:
        """
        Device Pool Temperature Down command.
        """

        class all_link_broadcast:
            """
            Device Pool Temperature Down all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Pool Temperature Down all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Pool Temperature Down all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Pool Temperature Down all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Pool Temperature Down broadcast command.
            """

        class direct:
            """
            Device Pool Temperature Down direct command.
            """

        class direct_ack:
            """
            Device Pool Temperature Down direct_ack command.
            """

        class direct_nak:
            """
            Device Pool Temperature Down direct_nak command.
            """

    class pool_temperature_up:
        """
        Device Pool Temperature Up command.
        """

        class all_link_broadcast:
            """
            Device Pool Temperature Up all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Pool Temperature Up all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Pool Temperature Up all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Pool Temperature Up all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Pool Temperature Up broadcast command.
            """

        class direct:
            """
            Device Pool Temperature Up direct command.
            """

        class direct_ack:
            """
            Device Pool Temperature Up direct_ack command.
            """

        class direct_nak:
            """
            Device Pool Temperature Up direct_nak command.
            """

    class product_data_request:
        """
        Device Product Data Request command.
        """

        class all_link_broadcast:
            """
            Device Product Data Request all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Product Data Request all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Product Data Request all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Product Data Request all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Product Data Request broadcast command.
            """

        class direct:
            """
            Device Product Data Request direct command.
            """

        class direct_ack:
            """
            Device Product Data Request direct_ack command.
            """

        class direct_nak:
            """
            Device Product Data Request direct_nak command.
            """

    class read_write_all_link_database:
        """
        Device Read/Write ALL-Link Database (ALDB) command.
        """

        class all_link_broadcast:
            """
            Device Read/Write ALL-Link Database (ALDB) all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Read/Write ALL-Link Database (ALDB) all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Read/Write ALL-Link Database (ALDB) all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Read/Write ALL-Link Database (ALDB) all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Read/Write ALL-Link Database (ALDB) broadcast command.
            """

        class direct:
            """
            Device Read/Write ALL-Link Database (ALDB) direct command.
            """

        class direct_ack:
            """
            Device Read/Write ALL-Link Database (ALDB) direct_ack command.
            """

        class direct_nak:
            """
            Device Read/Write ALL-Link Database (ALDB) direct_nak command.
            """

    class remote_set_button_tap:
        """
        Device Remote SET Button Tap command.
        """

        class all_link_broadcast:
            """
            Device Remote SET Button Tap all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Remote SET Button Tap all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Remote SET Button Tap all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Remote SET Button Tap all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Remote SET Button Tap broadcast command.
            """

        class direct:
            """
            Device Remote SET Button Tap direct command.
            """

        class direct_ack:
            """
            Device Remote SET Button Tap direct_ack command.
            """

        class direct_nak:
            """
            Device Remote SET Button Tap direct_nak command.
            """

    class reread_init_values:
        """
        Device Reread Init Values command.
        """

        class all_link_broadcast:
            """
            Device Reread Init Values all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Reread Init Values all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Reread Init Values all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Reread Init Values all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Reread Init Values broadcast command.
            """

        class direct:
            """
            Device Reread Init Values direct command.
            """

        class direct_ack:
            """
            Device Reread Init Values direct_ack command.
            """

        class direct_nak:
            """
            Device Reread Init Values direct_nak command.
            """

    class set_address_msb:
        """
        Device Set Address MSB command.
        """

        class all_link_broadcast:
            """
            Device Set Address MSB all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Set Address MSB all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Set Address MSB all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Set Address MSB all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Set Address MSB broadcast command.
            """

        class direct:
            """
            Device Set Address MSB direct command.
            """

        class direct_ack:
            """
            Device Set Address MSB direct_ack command.
            """

        class direct_nak:
            """
            Device Set Address MSB direct_nak command.
            """

    class set_all_link:
        """
        Device Set ALL-Link command.
        """

        class all_link_broadcast:
            """
            Device Set ALL-Link all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Set ALL-Link all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Set ALL-Link all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Set ALL-Link all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Set ALL-Link broadcast command.
            """

        class direct:
            """
            Device Set ALL-Link direct command.
            """

        class direct_ack:
            """
            Device Set ALL-Link direct_ack command.
            """

        class direct_nak:
            """
            Device Set ALL-Link direct_nak command.
            """

    class set_all_link_command_alias:
        """
        Device Set ALL-Link Command Alias command.
        """

        class all_link_broadcast:
            """
            Device Set ALL-Link Command Alias all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Set ALL-Link Command Alias all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Set ALL-Link Command Alias all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Set ALL-Link Command Alias all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Set ALL-Link Command Alias broadcast command.
            """

        class direct:
            """
            Device Set ALL-Link Command Alias direct command.
            """

        class direct_ack:
            """
            Device Set ALL-Link Command Alias direct_ack command.
            """

        class direct_nak:
            """
            Device Set ALL-Link Command Alias direct_nak command.
            """

    class set_device_text_string:
        """
        Device Set Device Text String command.
        """

        class all_link_broadcast:
            """
            Device Set Device Text String all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Set Device Text String all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Set Device Text String all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Set Device Text String all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Set Device Text String broadcast command.
            """

        class direct:
            """
            Device Set Device Text String direct command.
            """

        class direct_ack:
            """
            Device Set Device Text String direct_ack command.
            """

        class direct_nak:
            """
            Device Set Device Text String direct_nak command.
            """

    class set_operating_flags:
        """
        Device Set Operating Flags command.
        """

        class all_link_broadcast:
            """
            Device Set Operating Flags all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Set Operating Flags all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Set Operating Flags all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Set Operating Flags all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Set Operating Flags broadcast command.
            """

        class direct:
            """
            Device Set Operating Flags direct command.
            """

        class direct_ack:
            """
            Device Set Operating Flags direct_ack command.
            """

        class direct_nak:
            """
            Device Set Operating Flags direct_nak command.
            """

    class set_sprinkler_program:
        """
        Device Set Sprinkler Program command.
        """

        class all_link_broadcast:
            """
            Device Set Sprinkler Program all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Set Sprinkler Program all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Set Sprinkler Program all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Set Sprinkler Program all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Set Sprinkler Program broadcast command.
            """

        class direct:
            """
            Device Set Sprinkler Program direct command.
            """

        class direct_ack:
            """
            Device Set Sprinkler Program direct_ack command.
            """

        class direct_nak:
            """
            Device Set Sprinkler Program direct_nak command.
            """

    class sprinkler_control:
        """
        Device Sprinkler Control command.
        """

        class all_link_broadcast:
            """
            Device Sprinkler Control all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Sprinkler Control all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Sprinkler Control all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Sprinkler Control all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Sprinkler Control broadcast command.
            """

        class direct:
            """
            Device Sprinkler Control direct command.
            """

        class direct_ack:
            """
            Device Sprinkler Control direct_ack command.
            """

        class direct_nak:
            """
            Device Sprinkler Control direct_nak command.
            """

    class sprinkler_get_program_request:
        """
        Device Sprinkler Get Program Request command.
        """

        class all_link_broadcast:
            """
            Device Sprinkler Get Program Request all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Sprinkler Get Program Request all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Sprinkler Get Program Request all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Sprinkler Get Program Request all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Sprinkler Get Program Request broadcast command.
            """

        class direct:
            """
            Device Sprinkler Get Program Request direct command.
            """

        class direct_ack:
            """
            Device Sprinkler Get Program Request direct_ack command.
            """

        class direct_nak:
            """
            Device Sprinkler Get Program Request direct_nak command.
            """

    class sprinkler_get_program_response:
        """
        Device Sprinkler Get Program Response command.
        """

        class all_link_broadcast:
            """
            Device Sprinkler Get Program Response all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Sprinkler Get Program Response all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Sprinkler Get Program Response all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Sprinkler Get Program Response all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Sprinkler Get Program Response broadcast command.
            """

        class direct:
            """
            Device Sprinkler Get Program Response direct command.
            """

        class direct_ack:
            """
            Device Sprinkler Get Program Response direct_ack command.
            """

        class direct_nak:
            """
            Device Sprinkler Get Program Response direct_nak command.
            """

    class sprinkler_program_off:
        """
        Device Sprinkler Program Off command.
        """

        class all_link_broadcast:
            """
            Device Sprinkler Program Off all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Sprinkler Program Off all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Sprinkler Program Off all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Sprinkler Program Off all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Sprinkler Program Off broadcast command.
            """

        class direct:
            """
            Device Sprinkler Program Off direct command.
            """

        class direct_ack:
            """
            Device Sprinkler Program Off direct_ack command.
            """

        class direct_nak:
            """
            Device Sprinkler Program Off direct_nak command.
            """

    class sprinkler_program_on:
        """
        Device Sprinkler Program On command.
        """

        class all_link_broadcast:
            """
            Device Sprinkler Program On all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Sprinkler Program On all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Sprinkler Program On all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Sprinkler Program On all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Sprinkler Program On broadcast command.
            """

        class direct:
            """
            Device Sprinkler Program On direct command.
            """

        class direct_ack:
            """
            Device Sprinkler Program On direct_ack command.
            """

        class direct_nak:
            """
            Device Sprinkler Program On direct_nak command.
            """

    class sprinkler_valve_off:
        """
        Device Sprinkler Valve OFF command.
        """

        class all_link_broadcast:
            """
            Device Sprinkler Valve OFF all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Sprinkler Valve OFF all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Sprinkler Valve OFF all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Sprinkler Valve OFF all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Sprinkler Valve OFF broadcast command.
            """

        class direct:
            """
            Device Sprinkler Valve OFF direct command.
            """

        class direct_ack:
            """
            Device Sprinkler Valve OFF direct_ack command.
            """

        class direct_nak:
            """
            Device Sprinkler Valve OFF direct_nak command.
            """

    class sprinkler_valve_on:
        """
        Device Sprinkler Valve ON command.
        """

        class all_link_broadcast:
            """
            Device Sprinkler Valve ON all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Sprinkler Valve ON all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Sprinkler Valve ON all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Sprinkler Valve ON all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Sprinkler Valve ON broadcast command.
            """

        class direct:
            """
            Device Sprinkler Valve ON direct command.
            """

        class direct_ack:
            """
            Device Sprinkler Valve ON direct_ack command.
            """

        class direct_nak:
            """
            Device Sprinkler Valve ON direct_nak command.
            """

    class start_manual_change:
        """
        Device Start Manual Change command.
        """

        class all_link_broadcast:
            """
            Device Start Manual Change all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Start Manual Change all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Start Manual Change all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Start Manual Change all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Start Manual Change broadcast command.
            """

        class direct:
            """
            Device Start Manual Change direct command.
            """

        class direct_ack:
            """
            Device Start Manual Change direct_ack command.
            """

        class direct_nak:
            """
            Device Start Manual Change direct_nak command.
            """

    class status_request:
        """
        Device Status Request command.
        """

        class all_link_broadcast:
            """
            Device Status Request all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Status Request all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Status Request all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Status Request all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Status Request broadcast command.
            """

        class direct:
            """
            Device Status Request direct command.
            """

        class direct_ack:
            """
            Device Status Request direct_ack command.
            """

        class direct_nak:
            """
            Device Status Request direct_nak command.
            """

    class stop_manual_change:
        """
        Device Stop Manual Change command.
        """

        class all_link_broadcast:
            """
            Device Stop Manual Change all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Stop Manual Change all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Stop Manual Change all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Stop Manual Change all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Stop Manual Change broadcast command.
            """

        class direct:
            """
            Device Stop Manual Change direct command.
            """

        class direct_ack:
            """
            Device Stop Manual Change direct_ack command.
            """

        class direct_nak:
            """
            Device Stop Manual Change direct_nak command.
            """

    class thermostat_control:
        """
        Device Thermostat Control command.
        """

        class all_link_broadcast:
            """
            Device Thermostat Control all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Thermostat Control all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Thermostat Control all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Thermostat Control all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Thermostat Control broadcast command.
            """

        class direct:
            """
            Device Thermostat Control direct command.
            """

        class direct_ack:
            """
            Device Thermostat Control direct_ack command.
            """

        class direct_nak:
            """
            Device Thermostat Control direct_nak command.
            """

    class thermostat_get_zone_information:
        """
        Device Thermostat Get Zone Information command.
        """

        class all_link_broadcast:
            """
            Device Thermostat Get Zone Information all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Thermostat Get Zone Information all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Thermostat Get Zone Information all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Thermostat Get Zone Information all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Thermostat Get Zone Information broadcast command.
            """

        class direct:
            """
            Device Thermostat Get Zone Information direct command.
            """

        class direct_ack:
            """
            Device Thermostat Get Zone Information direct_ack command.
            """

        class direct_nak:
            """
            Device Thermostat Get Zone Information direct_nak command.
            """

    class thermostat_set_cool_setpoint:
        """
        Device Thermostat Set Cool Setpoint command.
        """

        class all_link_broadcast:
            """
            Device Thermostat Set Cool Setpoint all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Thermostat Set Cool Setpoint all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Thermostat Set Cool Setpoint all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Thermostat Set Cool Setpoint all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Thermostat Set Cool Setpoint broadcast command.
            """

        class direct:
            """
            Device Thermostat Set Cool Setpoint direct command.
            """

        class direct_ack:
            """
            Device Thermostat Set Cool Setpoint direct_ack command.
            """

        class direct_nak:
            """
            Device Thermostat Set Cool Setpoint direct_nak command.
            """

    class thermostat_set_heat_setpoint:
        """
        Device Thermostat Set Heat Setpoint command.
        """

        class all_link_broadcast:
            """
            Device Thermostat Set Heat Setpoint all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Thermostat Set Heat Setpoint all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Thermostat Set Heat Setpoint all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Thermostat Set Heat Setpoint all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Thermostat Set Heat Setpoint broadcast command.
            """

        class direct:
            """
            Device Thermostat Set Heat Setpoint direct command.
            """

        class direct_ack:
            """
            Device Thermostat Set Heat Setpoint direct_ack command.
            """

        class direct_nak:
            """
            Device Thermostat Set Heat Setpoint direct_nak command.
            """

    class thermostat_temperature_down:
        """
        Device Thermostat Temperature Down command.
        """

        class all_link_broadcast:
            """
            Device Thermostat Temperature Down all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Thermostat Temperature Down all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Thermostat Temperature Down all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Thermostat Temperature Down all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Thermostat Temperature Down broadcast command.
            """

        class direct:
            """
            Device Thermostat Temperature Down direct command.
            """

        class direct_ack:
            """
            Device Thermostat Temperature Down direct_ack command.
            """

        class direct_nak:
            """
            Device Thermostat Temperature Down direct_nak command.
            """

    class thermostat_temperature_up:
        """
        Device Thermostat Temperature Up command.
        """

        class all_link_broadcast:
            """
            Device Thermostat Temperature Up all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Thermostat Temperature Up all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Thermostat Temperature Up all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Thermostat Temperature Up all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Thermostat Temperature Up broadcast command.
            """

        class direct:
            """
            Device Thermostat Temperature Up direct command.
            """

        class direct_ack:
            """
            Device Thermostat Temperature Up direct_ack command.
            """

        class direct_nak:
            """
            Device Thermostat Temperature Up direct_nak command.
            """

    class trigger_all_link:
        """
        Device Trigger ALL-Link command.
        """

        class all_link_broadcast:
            """
            Device Trigger ALL-Link all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Trigger ALL-Link all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Trigger ALL-Link all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Trigger ALL-Link all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Trigger ALL-Link broadcast command.
            """

        class direct:
            """
            Device Trigger ALL-Link direct command.
            """

        class direct_ack:
            """
            Device Trigger ALL-Link direct_ack command.
            """

        class direct_nak:
            """
            Device Trigger ALL-Link direct_nak command.
            """

    class window_covering:
        """
        Device Window Covering command.
        """

        class all_link_broadcast:
            """
            Device Window Covering all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Window Covering all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Window Covering all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Window Covering all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Window Covering broadcast command.
            """

        class direct:
            """
            Device Window Covering direct command.
            """

        class direct_ack:
            """
            Device Window Covering direct_ack command.
            """

        class direct_nak:
            """
            Device Window Covering direct_nak command.
            """

    class window_covering_position:
        """
        Device Window Covering Position command.
        """

        class all_link_broadcast:
            """
            Device Window Covering Position all_link_broadcast command.
            """

        class all_link_cleanup:
            """
            Device Window Covering Position all_link_cleanup command.
            """

        class all_link_cleanup_ack:
            """
            Device Window Covering Position all_link_cleanup_ack command.
            """

        class all_link_cleanup_nak:
            """
            Device Window Covering Position all_link_cleanup_nak command.
            """

        class broadcast:
            """
            Device Window Covering Position broadcast command.
            """

        class direct:
            """
            Device Window Covering Position direct command.
            """

        class direct_ack:
            """
            Device Window Covering Position direct_ack command.
            """

        class direct_nak:
            """
            Device Window Covering Position direct_nak command.
            """

class send:
    """
    Send an Insteon Message
    """

    class cancel_all_linking:
        """
        Cancel ALL-Linking
        """

    class get_all_link_record_for_sender:
        """
        Get ALL-Link Record for Sender
        """

    class get_first_all_link_record:
        """
        Get First ALL-Link Record
        """

    class get_im_configuration:
        """
        Get IM Configuration
        """

    class get_im_info:
        """
        Get IM Info
        """

    class get_next_all_link_record:
        """
        Get Next ALL-Link Record
        """

    class led_off:
        """
        LED Off
        """

    class led_on:
        """
        LED On
        """

    class manage_all_link_record:
        """
        Manage ALL-Link Record
        """

    class reset_the_im:
        """
        Reset the IM
        """

    class rf_sleep:
        """
        RF Sleep
        """

    class send_all_link_command:
        """
        Send ALL-Link Command
        """

    class send_insteon_standard_or_extended_message:
        """
        Send INSTEON Standard or Extended Message
        """

    class send_x10:
        """
        Send X10
        """

    class set_host_device_category:
        """
        Set Host Device Category
        """

    class set_im_configuration:
        """
        Set IM Configuration
        """

    class set_insteon_ack_message_byte:
        """
        Set INSTEON ACK Message Byte
        """

    class set_insteon_ack_message_two_bytes:
        """
        Set INSTEON ACK Message Two Bytes
        """

    class set_insteon_nak_message_byte:
        """
        Set INSTEON NAK Message Byte
        """

    class start_all_linking:
        """
        Start ALL-Linking
        """


# End of topic tree definition. Note that application may load
# more than one definitions provider.
